name: chico_dagua
description: App para determinar a quantidade de agua necessaria para irrigacoes.
version: 1.3.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  path_provider: ^1.1.0
  package_info_plus: ^1.0.0
  scoped_model: ^1.0.1
  location: ^2.3.5
  geocoder: ^0.2.1
  dartdoc: any
  firebase_database: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - imgs/
  fonts:
    - family: Comfortaa
      fonts:
          - asset: fonts/Comfortaa-Regular.ttf
          - asset: fonts/Comfortaa-Bold.ttf